# Generated by Django 4.0.3 on 2022-03-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game/')),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='game/')),
            ],
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Yetakchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chat_id', models.IntegerField(default=0)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.mahalla')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=35, null=True)),
                ('uy', models.CharField(max_length=225, null=True)),
                ('chat_id', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.game')),
                ('mahalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.mahalla')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.viloyat')),
            ],
        ),
        migrations.AddField(
            model_name='mahalla',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tuman'),
        ),
    ]
