# Generated by Django 4.0.3 on 2022-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetakchi',
            name='password',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='yetakchi',
            name='username',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
