# Generated by Django 4.0.3 on 2022-03-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_yetakchi_password_yetakchi_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'menu'), (1, 'game'), (2, 'register'), (3, 'Ism'), (5, 'Telefon'), (6, 'viloyat'), (7, 'Tuman'), (8, 'mahalla'), (9, 'uy')], default=0),
        ),
    ]
