# Generated by Django 4.0.3 on 2022-03-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chat_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'game'), (1, 'name'), (2, 'phone'), (3, 'mahalla'), (4, 'uy'), (5, 'done')], default=0),
        ),
    ]
